"""ExportFinishedVideo node: persist finished video, cover, and publish package.

The cover is AI-generated by default (``cover.mode == "ai"``) when a real
``image.generate`` ProviderProfile + active secret exist; the frame-extracted
thumbnail is the fallback. A ``cover_frame_fallback`` degradation is emitted ONLY
when the AI capability was available (a real profile resolved) but the paid call
failed for this run — an actionable degradation. When no image profile is
configured at all the frame cover is the honest BASELINE (no AI capability to
degrade from) and no degradation is recorded; see ``_build_cover``.

The finished video's title and the AI cover's headline come from generated publish
copy (``_resolve_publish_copy`` → real ``llm.chat`` when armed, else a deterministic
derivation from the script). A copy/title failure is non-fatal: the video is already
produced, so it falls back to the deterministic copy rather than failing the export.
"""

from __future__ import annotations

import base64
import binascii
import hashlib
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

from packages.ai.gateway import ProviderCall
from packages.core.contracts import (
    Artifact,
    ArtifactKind,
    DegradationNotice,
    FinishedVideo,
    NodeStatus,
    ScriptVersion,
    VideoVersion,
    WarningCode,
)
from packages.core.storage.repository import new_id
from packages.core.workflow import NodeExecutionError, NodeOutput
from packages.media.assets import store_file
from packages.media.cover import (
    DEFAULT_COVER_SIZE,
    SEEDREAM_COVER_REQUEST_SIZE,
    CoverPromptInputs,
    build_cover_prompt,
)
from packages.media.cover_frame import BestPortraitFrame, select_best_portrait_frame
from packages.media.video.ffmpeg import (
    FfmpegCommandError,
    extract_frame_at_time,
    extract_thumbnails,
)
from packages.publishing.copy_llm import build_copy_llm_chat
from packages.publishing.copy_node import (
    PublishCopy,
    PublishCopyContext,
    derive_publish_copy,
    generate_publish_copy,
)
from packages.core.observability import record_funnel_event
from packages.production.finished_video_numbering import next_finished_video_number
from packages.production.pipeline._node_context import NodeContext
from packages.production.pipeline.degradation_policies import COVER_FALLBACK_POLICY

COVER_PROMPT_VERSION_ID = "prompt_cover_ai_cover_v1"
# Spec §10.1: the AI-cover prompt must resolve through the Prompt Registry binding
# (PublishCover.ai_cover), not be looked up by a hardcoded version id. We still
# tolerate a missing binding (degraded environments / bare test adapters) by
# falling back to the canonical seeded version so the cover never hard-fails on
# prompt resolution alone.
AI_COVER_NODE_ID = "PublishCover.ai_cover"
# Cover source-frame selection prefers clean intermediate tracks (no burned
# subtitles, no b-roll inserts) over the final composited video.
_COVER_SOURCE_KINDS = (ArtifactKind.video_lipsync, ArtifactKind.video_portrait_track)


@dataclass(frozen=True)
class _CoverReferenceImage:
    image_b64: str
    filename: str
    has_template: bool = False
    has_source_frame: bool = False
    source_frame_time_sec: float | None = None
    source_artifact_id: str | None = None
    reference_asset_id: str | None = None


def run(ctx: NodeContext) -> NodeOutput:
    state = ctx.state
    run = ctx.run
    repository = ctx.repository
    final = state.require(ArtifactKind.video_final)
    timeline = state.require(ArtifactKind.plan_timeline)
    style = state.require(ArtifactKind.plan_style)
    script = _resolve_script_version(state, repository)
    repository.scripts[script.id] = script
    video_artifact = ctx.artifact(
        ArtifactKind.video_finished,
        None,
        "uri-only",
        uri=final.uri,
        sha256=final.sha256,
        media_info=final.media_info,
    )
    copy, _copy_source, copy_invocation_id = _resolve_publish_copy(ctx, script)
    cover_artifact, cover_degradations, cover_invocation_ids, cover_extra_artifacts = _build_cover(
        ctx, final, copy
    )
    lipsync_provider_id, lipsync_fallback_used, lipsync_fallback_reason = (
        _resolve_lipsync_attribution(ctx)
    )
    finished = FinishedVideo(
        id=new_id("fv"),
        case_id=state.request.case_id,
        run_id=run.id,
        owner_user_id=_resolve_owner_user_id(run, repository),
        title=copy.title or state.request.title or script.title or "未命名成片",
        video_number=_next_video_number(repository, state.request.case_id),
        video_artifact=repository.artifact_ref(video_artifact.id),
        cover_artifact=repository.artifact_ref(cover_artifact.id),
        subtitle_artifact=(
            repository.artifact_ref(state.artifacts[ArtifactKind.subtitle_ass].id)
            if ArtifactKind.subtitle_ass in state.artifacts
            else None
        ),
        duration_sec=float(
            final.media_info.duration_sec
            if final.media_info and final.media_info.duration_sec
            else 0
        ),
        lipsync_provider_id=lipsync_provider_id,
        lipsync_fallback_used=lipsync_fallback_used,
        lipsync_fallback_reason=lipsync_fallback_reason,
    )
    repository.finished_videos[finished.id] = finished
    video_version = VideoVersion(
        id=new_id("vv"),
        case_id=state.request.case_id,
        script_version_id=script.id,
        finished_video_id=finished.id,
        timeline_plan_artifact_id=timeline.id,
        style_plan_artifact_id=style.id,
    )
    repository.video_versions[video_version.id] = video_version
    package_artifact = _create_publish_package_artifact(
        ctx,
        finished,
        description=copy.publish_content or state.request.publish_content,
    )
    return NodeOutput(
        status=NodeStatus.degraded if cover_degradations else NodeStatus.succeeded,
        artifacts=[video_artifact, cover_artifact, package_artifact, *cover_extra_artifacts],
        degradations=cover_degradations,
        provider_invocation_ids=cover_invocation_ids
        + ([copy_invocation_id] if copy_invocation_id else []),
    )


def _create_publish_package_artifact(
    ctx: NodeContext,
    finished: FinishedVideo,
    *,
    description: str,
) -> Artifact:
    repository = ctx.repository
    run = ctx.run
    node_run = ctx.node_run
    package = repository.create_publish_package_from_finished_video(
        finished,
        title=finished.title,
        description=description,
    )
    repository.create_event(
        "workflow.finished_video.created",
        "run",
        run.id,
        {"finished_video_id": finished.id, "publish_package_id": package.id},
        dedupe_key=f"finished_video:{finished.id}",
        event_type="artifact_created",
        node_id=node_run.node_id,
        status=NodeStatus.running.value,
        message=f"Finished video {finished.id} created.",
    )
    record_funnel_event(
        repository,
        event_type="finished_video_created",
        job_id=run.job_id,
        run_id=run.id,
        finished_video_id=finished.id,
        publish_package_id=package.id,
        dedupe_key=f"{finished.id}:finished_video_created",
        event_time=finished.created_at,
    )
    return ctx.artifact(
        ArtifactKind.publish_package,
        package.model_dump(mode="json"),
        "PublishPackageArtifact.v1",
    )


def _resolve_owner_user_id(run, repository) -> str | None:
    """Resolve the finished video's owner at write time (创建即落 owner, spec §3.5).

    Prefers ``run.requested_by`` (set to ``job.created_by`` at submission); falls back
    to looking the job up in the repository when the run carries no requester. Returns
    ``None`` only when neither yields an owner so orphaned产出 stay NULL (admin-only视图).
    """
    if run.requested_by:
        return run.requested_by
    job = repository.jobs.get(run.job_id)
    if job is not None:
        return job.created_by
    return None


def _next_video_number(repository, case_id: str) -> str:
    return next_finished_video_number(
        video.video_number
        for video in repository.finished_videos.values()
        if video.case_id == case_id
    )


def _resolve_script_version(state, repository) -> ScriptVersion:
    """Link the adopted ScriptVersion for this run.

    When the request references an existing adopted ScriptVersion (e.g. one created
    by adopting a Case Agent draft) we REUSE that row so its provenance
    (``adopted_from_draft_id``, original creative-intent link) survives and it is no
    longer orphaned. Only when no matching ScriptVersion is loaded do we fabricate a
    fresh one under the requested (or a new) id.
    """
    requested_id = state.request.script_version_id
    if requested_id:
        existing = repository.scripts.get(requested_id)
        if existing is not None and existing.case_id == state.request.case_id:
            return existing
    creative_intent_artifact_id = (
        state.artifacts.get(ArtifactKind.creative_intent).id
        if ArtifactKind.creative_intent in state.artifacts
        else None
    )
    return ScriptVersion(
        id=requested_id or new_id("script"),
        case_id=state.request.case_id,
        title=state.request.title or "未命名成片",
        script=state.request.script,
        creative_intent_artifact_id=creative_intent_artifact_id,
    )


def _resolve_lipsync_attribution(ctx: NodeContext) -> tuple[str | None, bool, str | None]:
    """Resolve which lipsync provider produced this finished video from the run's
    LipSyncReportArtifact (HeyGem-primary → VideoReTalk-fallback).

    Returns ``(provider_id, fallback_used, fallback_reason)``. Falls back to
    ``(None, False, None)`` whenever attribution cannot be established honestly:
    no report (lipsync absent in this template), the report is ``skipped`` (request
    disabled / sandbox pass-through), no ``provider_profile_id`` recorded, or the
    profile is no longer resolvable in the repository. ``provider_id`` is the
    ProviderProfile.provider_id (e.g. ``runninghub.heygem`` / ``dashscope.videoretalk``),
    NOT the profile id, so the UI can map it to a stable, profile-agnostic label."""
    report = ctx.state.artifacts.get(ArtifactKind.lipsync_report)
    payload = report.payload if report is not None else None
    if not isinstance(payload, dict):
        return None, False, None
    # A skipped report means no real lipsync provider produced the video (request
    # disabled / sandbox pass-through) -> no attribution to surface.
    if payload.get("skipped"):
        return None, False, None
    profile_id = payload.get("provider_profile_id")
    if not isinstance(profile_id, str) or not profile_id:
        return None, False, None
    profile = ctx.repository.provider_profiles.get(profile_id)
    if profile is None:
        return None, False, None
    fallback_used = bool(payload.get("fallback_from"))
    fallback_reason = payload.get("fallback_reason") if fallback_used else None
    return profile.provider_id, fallback_used, fallback_reason


def _build_cover(
    ctx: NodeContext, final: Artifact, copy: PublishCopy
) -> tuple[Artifact, list[DegradationNotice], list[str], list[Artifact]]:
    """Resolve the cover artifact, returning
    ``(artifact, degradations, invocation_ids, extra_artifacts)``.

    AI cover is the default and the frame cover the fallback; the degradation
    semantics (when ``cover_frame_fallback`` is and isn't emitted) are explained in
    the module docstring."""
    request = ctx.state.request
    wants_ai = request.cover.mode == "ai"
    profile_ids = ctx.image_cover_profile_ids(request) if wants_ai else []
    if profile_ids:
        invocation_ids: list[str] = []
        extra_artifacts: list[Artifact] = []
        for index, profile_id in enumerate(profile_ids):
            ai_cover, attempt_invocation_ids, request_artifact = _generate_ai_cover(
                ctx, profile_id, copy
            )
            invocation_ids.extend(attempt_invocation_ids)
            if request_artifact is not None:
                extra_artifacts.append(request_artifact)
            if ai_cover is not None:
                if isinstance(ai_cover.payload, dict):
                    payload = dict(ai_cover.payload)
                    payload["attempted_provider_profile_ids"] = profile_ids[: index + 1]
                    payload["provider_invocation_ids"] = invocation_ids
                    if index > 0:
                        payload["fallback_from_provider_profile_ids"] = profile_ids[:index]
                    ai_cover = _apply_cover_source_payload(ctx, ai_cover, payload)
                return ai_cover, [], invocation_ids, extra_artifacts
        return (
            _frame_cover(
                ctx,
                final,
                reason="ai_failed",
                attempted_provider_profile_ids=profile_ids,
                provider_invocation_ids=invocation_ids,
            ),
            [
                DegradationNotice(
                    code=WarningCode.cover_frame_fallback,
                    message="AI cover generation failed; used frame-based cover.",
                    node_id=ctx.node_run.node_id,
                    policy_id=COVER_FALLBACK_POLICY.id,
                )
            ],
            invocation_ids,
            extra_artifacts,
        )
    reason = "ai_unavailable" if wants_ai else "requested_frame"
    return _frame_cover(ctx, final, reason=reason), [], [], []


def _resolve_publish_copy(
    ctx: NodeContext, script: ScriptVersion
) -> tuple[PublishCopy, str, str | None]:
    """Generate the publish copy (title + publish_content + cover title/subtitle) for
    this finished video. Uses a real ``llm.chat`` provider when armed, else the
    deterministic derivation. A provider/schema failure is NON-fatal: the finished
    video is already produced, so we fall back to the deterministic copy rather than
    failing the export over a title."""
    request = ctx.state.request
    context = PublishCopyContext(
        script=script.script or "",
        case_name=request.case_id,
        description=request.publish_content,
    )
    registry = ctx.prompt_registry
    llm_chat = build_copy_llm_chat(
        gateway=ctx.provider_gateway,
        repository=ctx.repository,
        prompt_registry=registry,
        case_id=ctx.run.case_id,
        run_id=ctx.run.id,
        node_run_id=ctx.node_run.id,
    )
    try:
        return generate_publish_copy(context, llm_chat=llm_chat)
    except NodeExecutionError:
        return derive_publish_copy(context), "deterministic", None


def _frame_cover(
    ctx: NodeContext,
    final: Artifact,
    *,
    reason: str,
    attempted_provider_profile_ids: list[str] | None = None,
    provider_invocation_ids: list[str] | None = None,
) -> Artifact:
    try:
        with tempfile.TemporaryDirectory(prefix="cutagent-cover-") as directory:
            thumbnails = extract_thumbnails(
                ctx.artifact_path(final),
                Path(directory),
                labels=("first", "mid"),
            )
            selected = thumbnails[-1]
            cover_stored = store_file(ctx.object_store(), selected.path, purpose="covers")
    except FfmpegCommandError as exc:
        raise NodeExecutionError(exc.error_code, "Finished video cover extraction failed.") from exc
    artifact = ctx.artifact(
        ArtifactKind.cover_image,
        _cover_source_payload(
            source="frame",
            reason=reason,
            source_artifact_id=final.id,
            attempted_provider_profile_ids=attempted_provider_profile_ids,
            provider_invocation_ids=provider_invocation_ids,
        ),
        "CoverImageArtifact.v1",
        uri=cover_stored.ref.uri,
        sha256=cover_stored.sha256,
        media_info=selected.media_info,
    )
    return artifact


def _resolve_cover_prompt_version_id(ctx: NodeContext) -> str | None:
    """Resolve the AI-cover prompt version through the registry binding (Spec §10.1).

    Returns the bound, published version id when ``PublishCover.ai_cover`` is bound;
    otherwise falls back to the canonical seeded version id if that version exists,
    else ``None`` (no usable prompt -> caller renders with the in-code default).

    Resolution is driven off the repository's bindings (via PromptRegistry) so the
    node no longer looks the version up by a hardcoded id, satisfying the
    no-hardcoded-prod-prompt rule regardless of how the runtime adapter is wired."""
    registry = ctx.prompt_registry
    try:
        _binding, version = registry.resolve_published_version(
            node_id=AI_COVER_NODE_ID,
            case_id=ctx.run.case_id,
        )
        return version.id
    except NodeExecutionError:
        pass
    if COVER_PROMPT_VERSION_ID in ctx.repository.prompt_versions:
        return COVER_PROMPT_VERSION_ID
    return None


def _generate_ai_cover(
    ctx: NodeContext, profile_id: str, copy: PublishCopy
) -> tuple[Artifact | None, list[str], Artifact | None]:
    """Generate the AI cover via the gateway. Returns ``(None, invocation_ids)`` on any
    provider failure so the caller can fall back to the frame cover.

    When the request references an uploaded ``cover_template`` MediaAsset
    (``cover.reference_asset_id``), its image conditions the cover: ``has_template``
    flips the prompt to follow the reference style/layout and the template bytes are
    forwarded to the image-edit reference path so the uploaded style actually takes
    effect (mirrors the origin ``generate_publish_cover(template_id=...)``)."""
    state = ctx.state
    run = ctx.run
    node_run = ctx.node_run
    invocation_ids: list[str] = []
    template = _resolve_cover_template(ctx)
    reference = _build_cover_reference_image(ctx, template)
    version_id = _resolve_cover_prompt_version_id(ctx)
    version = ctx.repository.prompt_versions.get(version_id) if version_id is not None else None
    profile = ctx.repository.provider_profiles.get(profile_id)
    generation_size = _cover_generation_size(profile)
    template_content = (
        _normalize_cover_prompt_template(version.content) if version is not None else None
    )
    prompt = build_cover_prompt(
        CoverPromptInputs(
            title=copy.cover_title or copy.title or state.request.title or "",
            subtitle=copy.cover_subtitle or None,
            description=copy.publish_content or state.request.publish_content,
            case_name=state.request.case_id,
            has_source_frame=bool(reference and reference.has_source_frame),
            has_template=bool(reference and reference.has_template),
            size=generation_size,
        ),
        template=template_content,
    )
    call_input: dict = {"prompt": prompt}
    if profile is not None and profile.provider_id == "volcengine.seedream":
        call_input["size"] = generation_size
    if reference is not None:
        call_input["reference_image_b64"] = reference.image_b64
        call_input["reference_filename"] = reference.filename
        call_input["template_image_b64"] = reference.image_b64
        call_input["template_filename"] = reference.filename
        if reference.source_frame_time_sec is not None:
            call_input["source_frame_time_sec"] = round(reference.source_frame_time_sec, 3)
    request_artifact = _record_ai_cover_request_artifact(
        ctx=ctx,
        profile_id=profile_id,
        profile=profile,
        version_id=version.id if version is not None else None,
        copy=copy,
        prompt=prompt,
        generation_size=generation_size,
        reference=reference,
        call_input=call_input,
    )
    invocation, result = ctx.provider_gateway.invoke(
        ProviderCall(
            case_id=run.case_id,
            run_id=run.id,
            node_run_id=node_run.id,
            provider_profile_id=profile_id,
            capability_id="image.generate",
            prompt_version_id=version.id if version is not None else None,
            input=call_input,
            idempotency_key=f"cover-{run.id}-{_provider_key(profile_id)}",
        )
    )
    invocation_ids.append(invocation.id)
    if result is None or invocation.error:
        return None, invocation_ids, request_artifact
    if reference is not None and result.output.get("reference_image_used") is False:
        return None, invocation_ids, request_artifact
    artifact_id = result.output.get("cover_artifact_id")
    if not isinstance(artifact_id, str) or artifact_id not in ctx.repository.artifacts:
        return None, invocation_ids, request_artifact
    artifact = _apply_cover_source_payload(
        ctx,
        ctx.repository.artifacts[artifact_id],
        _cover_source_payload(
            source="ai",
            provider_profile_id=profile_id,
            provider_id=getattr(profile, "provider_id", None),
            provider_label=_cover_provider_label(getattr(profile, "provider_id", None)),
            model_id=getattr(profile, "model_id", None),
            provider_invocation_id=invocation.id,
            prompt_version_id=version.id if version is not None else None,
            size=generation_size,
        ),
    )
    return artifact, invocation_ids, request_artifact


def _record_ai_cover_request_artifact(
    *,
    ctx: NodeContext,
    profile_id: str,
    profile,
    version_id: str | None,
    copy: PublishCopy,
    prompt: str,
    generation_size: str,
    reference: _CoverReferenceImage | None,
    call_input: dict,
) -> Artifact:
    payload = {
        "capability_id": "image.generate",
        "provider_profile_id": profile_id,
        "provider_id": getattr(profile, "provider_id", None),
        "model_id": getattr(profile, "model_id", None),
        "prompt_version_id": version_id,
        "size": generation_size,
        "cover_title": copy.cover_title or copy.title or ctx.state.request.title or "",
        "cover_subtitle": copy.cover_subtitle or "",
        "publish_title": copy.title or "",
        "publish_content": copy.publish_content or ctx.state.request.publish_content or "",
        "prompt": prompt,
        "request_json": _sanitize_image_call_input(call_input),
        "reference": _cover_reference_snapshot(reference, ctx.state.request.cover.reference_asset_id),
    }
    return ctx.artifact(
        ArtifactKind.provider_raw_request,
        payload,
        "ImageGenerationRequestSnapshot.v1",
    )


def _sanitize_image_call_input(call_input: dict) -> dict:
    sanitized: dict = {}
    for key, value in call_input.items():
        if key.endswith("_image_b64") and isinstance(value, str):
            sanitized[key] = _b64_digest_summary(value)
        else:
            sanitized[key] = value
    return sanitized


def _cover_reference_snapshot(
    reference: _CoverReferenceImage | None,
    request_reference_asset_id: str | None,
) -> dict:
    if reference is None:
        return {"provided": False, "request_reference_asset_id": request_reference_asset_id}
    return {
        "provided": True,
        "filename": reference.filename,
        "has_template": reference.has_template,
        "has_source_frame": reference.has_source_frame,
        "source_frame_time_sec": reference.source_frame_time_sec,
        "source_artifact_id": reference.source_artifact_id,
        "reference_asset_id": reference.reference_asset_id or request_reference_asset_id,
        "image_b64": _b64_digest_summary(reference.image_b64),
    }


def _b64_digest_summary(value: str) -> dict:
    try:
        raw = base64.b64decode(value)
    except (binascii.Error, ValueError):
        raw = value.encode("utf-8")
    return {
        "omitted": True,
        "encoding": "base64",
        "length": len(value),
        "sha256": hashlib.sha256(raw).hexdigest(),
    }


def _cover_generation_size(profile) -> str:
    if profile is not None and profile.provider_id == "volcengine.seedream":
        return SEEDREAM_COVER_REQUEST_SIZE
    return DEFAULT_COVER_SIZE


def _provider_key(profile_id: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]+", "-", profile_id).strip("-") or "image"


def _cover_provider_label(provider_id: str | None) -> str | None:
    if provider_id == "openai.image":
        return "image2"
    if provider_id == "volcengine.seedream":
        return "seedream"
    return provider_id


def _cover_source_payload(
    *,
    source: str,
    reason: str | None = None,
    source_artifact_id: str | None = None,
    attempted_provider_profile_ids: list[str] | None = None,
    provider_invocation_ids: list[str] | None = None,
    provider_profile_id: str | None = None,
    provider_id: str | None = None,
    provider_label: str | None = None,
    model_id: str | None = None,
    provider_invocation_id: str | None = None,
    prompt_version_id: str | None = None,
    size: str | None = None,
) -> dict:
    payload = {
        "source": source,
        "reason": reason,
        "source_artifact_id": source_artifact_id,
        "attempted_provider_profile_ids": attempted_provider_profile_ids or [],
        "provider_invocation_ids": provider_invocation_ids or [],
        "provider_profile_id": provider_profile_id,
        "provider_id": provider_id,
        "provider_label": provider_label,
        "model_id": model_id,
        "provider_invocation_id": provider_invocation_id,
        "prompt_version_id": prompt_version_id,
        "size": size,
    }
    return {key: value for key, value in payload.items() if value is not None}


def _apply_cover_source_payload(ctx: NodeContext, artifact: Artifact, payload: dict) -> Artifact:
    artifact.payload_schema = "CoverImageArtifact.v1"
    artifact.payload = payload
    ctx.repository.artifacts[artifact.id] = artifact
    return artifact


def _normalize_cover_prompt_template(content: str) -> str:
    return (
        content.replace(
            "Create one polished vertical Chinese short-video cover image at {size}.",
            "Create one polished vertical 9:16 Chinese short-video cover image at {size}.",
        )
        .replace("center-cropped to 3:4", "center-cropped to 9:16")
        .replace("3:4 preview", "9:16 preview")
        .replace("尺寸为 3:4", "尺寸为 9:16")
        .replace("居中裁切为 3:4", "居中裁切为 9:16")
    )


def _build_cover_reference_image(
    ctx: NodeContext,
    template: tuple[str, str] | None,
) -> _CoverReferenceImage | None:
    source_frame = _select_cover_source_frame(ctx)
    template_ref = (
        _CoverReferenceImage(
            image_b64=template[0],
            filename=template[1],
            has_template=True,
            has_source_frame=False,
            reference_asset_id=ctx.state.request.cover.reference_asset_id,
        )
        if template is not None
        else None
    )
    if template_ref is not None and source_frame is not None:
        # Both present: combine into a two-panel reference board. If combining
        # fails (cv2 missing / decode error), prefer the user's explicitly
        # uploaded template over the auto-selected source frame -- an uploaded
        # cover template is an explicit user choice that must not be dropped.
        return _combine_cover_reference_board(template_ref, source_frame) or template_ref
    return source_frame or template_ref


def _select_cover_source_frame(ctx: NodeContext) -> _CoverReferenceImage | None:
    """Pick the cover reference frame from the cleanest readable track.

    Prefer subtitle-free / b-roll-free tracks (lipsync -> portrait), but keep trying
    later sources when an earlier artifact exists yet cannot be locally decoded.
    """
    for source in _cover_source_candidates(ctx):
        best = _pick_best_portrait_frame(ctx, source)
        if best is not None:
            face_frame = _extract_cover_source_frame(ctx, source, time_sec=best.time_sec)
            if face_frame is not None:
                return face_frame
        fallback_frame = _extract_cover_source_frame(ctx, source)
        if fallback_frame is not None:
            return fallback_frame
    return None


def _cover_source_candidates(ctx: NodeContext) -> list[Artifact]:
    """Readable-source priority: lipsync -> portrait -> final, de-duped by artifact id."""
    artifacts = ctx.state.artifacts
    sources: list[Artifact] = []
    seen: set[str] = set()
    for kind in _COVER_SOURCE_KINDS:
        artifact = artifacts.get(kind)
        if artifact is not None and artifact.id not in seen:
            sources.append(artifact)
            seen.add(artifact.id)
    final = ctx.state.require(ArtifactKind.video_final)
    if final.id not in seen:
        sources.append(final)
    return sources


def _pick_best_portrait_frame(ctx: NodeContext, source: Artifact) -> BestPortraitFrame | None:
    duration = float(
        source.media_info.duration_sec
        if source.media_info and source.media_info.duration_sec
        else 0
    )
    try:
        video_path = ctx.artifact_path(source)
    except Exception:
        return None
    try:
        with tempfile.TemporaryDirectory(prefix="cutagent-cover-pick-") as directory:
            return select_best_portrait_frame(str(video_path), duration, temp_dir=directory)
    except (FfmpegCommandError, OSError):
        return None


def _extract_cover_source_frame(
    ctx: NodeContext,
    source: Artifact,
    *,
    time_sec: float | None = None,
) -> _CoverReferenceImage | None:
    point = time_sec if time_sec is not None else _cover_reference_time_sec(source)
    try:
        with tempfile.TemporaryDirectory(prefix="cutagent-cover-source-") as directory:
            output = Path(directory) / "source-frame.png"
            frame = extract_frame_at_time(ctx.artifact_path(source), output, time_sec=point)
            data = frame.path.read_bytes()
    except Exception:
        return None
    if not data:
        return None
    return _CoverReferenceImage(
        image_b64=base64.b64encode(data).decode("ascii"),
        filename="source-frame.png",
        has_template=False,
        has_source_frame=True,
        source_frame_time_sec=point,
        source_artifact_id=source.id,
    )


def _cover_reference_time_sec(final: Artifact) -> float:
    duration = float(
        final.media_info.duration_sec if final.media_info and final.media_info.duration_sec else 0
    )
    return max(0.0, duration / 2.0)


def _combine_cover_reference_board(
    template: _CoverReferenceImage,
    source_frame: _CoverReferenceImage,
) -> _CoverReferenceImage | None:
    try:
        import cv2  # type: ignore
        import numpy as np  # type: ignore

        template_image = _decode_reference_image(cv2, np, template.image_b64)
        source_image = _decode_reference_image(cv2, np, source_frame.image_b64)
        if template_image is None or source_image is None:
            return None
        target_height = 1024
        template_resized = _resize_reference_to_height(cv2, template_image, target_height)
        source_resized = _resize_reference_to_height(cv2, source_image, target_height)
        separator = np.full((target_height, 16, 3), 245, dtype=np.uint8)
        board = np.hstack([template_resized, separator, source_resized])
        ok, encoded = cv2.imencode(".png", board)
        if not ok:
            return None
    except Exception:
        return None
    return _CoverReferenceImage(
        image_b64=base64.b64encode(bytes(encoded)).decode("ascii"),
        filename="cover-reference-board.png",
        has_template=True,
        has_source_frame=True,
        source_frame_time_sec=source_frame.source_frame_time_sec,
        source_artifact_id=source_frame.source_artifact_id,
        reference_asset_id=template.reference_asset_id,
    )


def _decode_reference_image(cv2, np, image_b64: str):
    try:
        data = base64.b64decode(image_b64)
    except (binascii.Error, ValueError):
        return None
    if not data:
        return None
    array = np.frombuffer(data, dtype=np.uint8)
    return cv2.imdecode(array, cv2.IMREAD_COLOR)


def _resize_reference_to_height(cv2, image, target_height: int):
    height, width = image.shape[:2]
    if height <= 0 or width <= 0:
        return image
    target_width = max(1, round(width * (target_height / height)))
    return cv2.resize(image, (target_width, target_height), interpolation=cv2.INTER_AREA)


def _resolve_cover_template(ctx: NodeContext) -> tuple[str, str] | None:
    """Return ``(base64_image, filename)`` for the requested cover-template asset, or
    ``None`` when no reference is set or it cannot be resolved (the cover then falls
    back to template-free generation rather than failing the whole node)."""
    asset_id = ctx.state.request.cover.reference_asset_id
    if not asset_id:
        return None
    try:
        artifact = ctx.source_artifact_for_asset(asset_id)
        path = ctx.artifact_path(artifact)
        data = path.read_bytes()
    except (NodeExecutionError, FileNotFoundError, OSError):
        return None
    if not data:
        return None
    filename = Path(path).name or "cover-template.jpg"
    return base64.b64encode(data).decode("ascii"), filename
